name: settings_new_look
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.8
  flutter_bloc: ^7.3.0
  http: ^0.13.3
  connectivity: ^2.0.2
  rflutter_alert: ^2.0.4
  flutter_conditional_rendering: ^2.0.0






dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Cairo-Regular
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
    - family: Cairo-SemiBold
      fonts:
        - asset: assets/fonts/Cairo-SemiBold.ttf
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
  assets:
    - assets/